### ISSUE TITLE
Enable option "Require pull request reviews before merging" for master branch

### ISSUE THREAD

**Issue by AMyachev** [Ann-Ageeva/Sound-recognition#1]
link: https://ru.stackoverflow.com/questions/723529/%D0%97%D0%B0%D1%89%D0%B8%D1%82%D0%B8%D1%82%D1%8C-%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%BD%D1%83%D1%8E-%D0%B2%D0%B5%D1%82%D0%BA%D1%83-git-%D0%BE%D1%82-%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by AMyachev** [comment]
@Ann-Ageeva need update

**Comment by Ann-Ageeva** [comment]
This option is now called "Require pull request reviews before merging".

**Comment by Ann-Ageeva** [comment]
https://habr.com/ru/post/266381/

**Comment by AMyachev** [comment]
@Ann-Ageeva you enable it?

**Comment by Ann-Ageeva** [comment]
@AMyachev Yes

**Comment by AMyachev** [comment]
Cool, please close the issue
