### ISSUE TITLE
Add a document describing the user's scenario with our system

### ISSUE THREAD

**Issue by AMyachev** [Ann-Ageeva/Sound-recognition#10]
Детали:

-  клонируешь репозиторий
- создаёшь свою ветку
- создаёшь папку docs в корне проекта
- создаёшь файл со сценарием в формате .md (как readme.md)
- добавляешь его к отслеживаемому состоянию гита
- отправляешь изменения на ветку в удалённом репозитории
- открываешь PR с твоей вновь созданной ветки в мастер
- запрашиваешь ревью у команды
- делаешь изменения, если они требуются, иначе мержишь в мастер

**Comment by Ann-Ageeva** [comment]
This is a book about use cases. 
Alistair Cockburn - Writing effective use cases.

**Comment by Ann-Ageeva** [comment]
https://dou.ua/lenta/articles/use-cases/

**Comment by Ann-Ageeva** [comment]
https://medium.com/@anastasiapurdes/%D0%BA%D0%B0%D0%BA-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-user-story-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B8-%D0%BA%D0%B5%D0%B9%D1%81%D1%8B-28cf1240624f

**Comment by Ann-Ageeva** [comment]
https://habr.com/ru/company/luxoft/blog/312188/

**Comment by Ann-Ageeva** [comment]
* нужен список инструментов, которые мы будем использовать для нашей задачи (ограничений от заказчика нет - поэтому мы можем написать всевозможные альтернативы, а потом выбрать их)
* нужны ограничения на клиентскую часть и на серверную по железу и необходимому предустановленному софту (от заказчика их нет, возможно, мы их можем поставить, когда получим хоть какое-нибудь рабочее решение)
