### ISSUE TITLE
Create a Client-Server part

### ISSUE THREAD

**Issue by Merilla** [Ann-Ageeva/Sound-recognition#13]
Must be done:
1) Create API for requests and response
2) Create base UI

**Comment by AMyachev** [comment]
Пиши только на питоне 3
--
Отправлено из Mail.ru для Android среда, 04 марта 2020г., 08:29 +03:00 от Ilya Shemetov  notifications@github.com :

**Comment by Merilla** [comment]
Only Python 3 solution
Creating a Client-Server part with a console app (the Server should receive 2 samples)
The Client can give the opportunity to use microphones
The Client has a basic UI

**Comment by Merilla** [comment]
DONE: Creating a Client-Server part with a console app (the Server should receive 2 samples)

**Comment by Merilla** [comment]
DONE: The Client has a basic UI

**Comment by AMyachev** [comment]
@Merilla nice! I'm waiting for PR with this implementation from you.

**Comment by Merilla** [comment]
DONE: The Client can give the opportunity to use microphones
