### ISSUE TITLE
Search for libraries to decompose sound into a Fourier series #9

### ISSUE THREAD

**Issue by AMyachev** [Ann-Ageeva/Sound-recognition#9]

**Comment by AMyachev** [comment]
@NikitaVashchuk need update

**Comment by NikitaVashchuk** [comment]
http://old.pynsk.ru/posts/2015/Nov/09/matematika-v-python-preobrazovanie-fure/#.XlvAj25uJet - Дискретное преобразование Фурье
https://proglib.io/p/python-music-classifier/ - Обработка звука

**Comment by AMyachev** [comment]
@NikitaVashchuk give me a short overview of these two links. We need a list of libraries, input formats,  complexity and so on. (**Note**: you should make the search for c++ also)

**Comment by AMyachev** [comment]
We also agreed that the main language will be English (this related to Github)
